spring.application.name=subscription-manager


# 1. Conxion data to the database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:Suscription
spring.datasource.username=Manager
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. Configuration of Hibernate
# 'none' because the tables are created in the sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=9090