DROP TABLE USERS CASCADE CONSTRAINTS

CREATE TABLE USERS (
USERID NUMBER(10) PRIMARY KEY,
USERNAME VARCHAR2(30)NOT NULL,
LASTNAME VARCHAR2(50)NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
DNI VARCHAR2(12) NOT NULL,
USRPASS VARCHAR2(255) NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE,
CONSTRAINT UQ_USREMAIL UNIQUE (EMAIL),
CONSTRAINT UQ_DNI UNIQUE (DNI)
);


CREATE TABLE PLANS (
PLANID NUMBER(10) PRIMARY KEY,
PLANNAME VARCHAR2(40) NOT NULL,
PRICE NUMBER(10,2)NOT NULL,
PLANDURATION NUMBER(3) NOT NULL,
CONSTRAINT UQ_PLANNAME UNIQUE (PLANNAME),
CONSTRAINT CH_PRICE CHECK (PRICE > 0),
CONSTRAINT CH_DURATION CHECK (PLANDURATION > 0)
);

CREATE TABLE SUBSCRIPTION (
SUBSCRIPTIONID NUMBER(10) PRIMARY KEY,
DATESTART DATE DEFAULT SYSDATE ,
DATEEND DATE ,
USERID NUMBER(10) NOT NULL,
PLANID NUMBER(10) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES USERS(USERID),
CONSTRAINT FK_PLANID FOREIGN KEY(PLANID) REFERENCES PLANS(PLANID)
);

CREATE INDEX IDX_FK_USERID ON SUBSCRIPTION(USERID);
CREATE INDEX IDX_FK_PLANID ON SUBSCRIPTION(PLANID);



CREATE OR REPLACE TRIGGER DATE_END
BEFORE INSERT ON SUBSCRIPTION
FOR EACH ROW 
DECLARE
    V_DURATION NUMBER;
BEGIN
    SELECT PLANDURATION INTO V_DURATION FROM PLANS WHERE PLANID =:NEW.PLANID;
    
    IF :NEW.DATESTART IS NULL THEN
        :NEW.DATESTART := SYSDATE;
    END IF;

    :NEW.DATEEND := ADD_MONTHS(:NEW.DATESTART, V_DURATION);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error: THE PLANID DOESNT EXIST.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'UNKOWN ERROR IN THE TRIGGER.');
END;
/