DROP TABLE USERS CASCADE CONSTRAINTS

CREATE TABLE USERS (
USERID NUMBER(10) PRIMARY KEY,
USERNAME VARCHAR2(30)NOT NULL,
LASTNAME VARCHAR2(50)NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
DNI VARCHAR2(12) NOT NULL,
USRPASS VARCHAR2(255) NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE,
CONSTRAINT UQ_USREMAIL UNIQUE (EMAIL),
CONSTRAINT UQ_DNI UNIQUE (DNI)
);


CREATE TABLE PLANS (
PLANID NUMBER(10) PRIMARY KEY,
PLANNAME VARCHAR2(40) NOT NULL,
PRICE NUMBER(10,2)NOT NULL,
PLANDURATION NUMBER(3) NOT NULL,
CONSTRAINT UQ_PLANNAME UNIQUE (PLANNAME)
);

CREATE TABLE SUBSCRIPTION (
SUBSCRIPTIONID NUMBER(10) PRIMARY KEY,
DATESTART DATE DEFAULT SYSDATE ,
DATEEND DATE ,
USERID NUMBER(10) NOT NULL,
PLANID NUMBER(10) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES USERS(USERID),
CONSTRAINT FK_PLANID FOREIGN KEY(PLANID) REFERENCES PLANS(PLANID)
);